on: [pull_request]
name: Test with PRO features
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test client with nexus3 instance
        env:
          NEXUS3_LICENSE_B64_ENCODED: ${{ secrets.NEXUS3_LICENSE_B64_ENCODED }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        run: |
          echo "${NEXUS3_LICENSE_B64_ENCODED}" | base64 -d > scripts/license.lic
          make start-services

          test -s scripts/license.lic || export SKIP_PRO_TESTS="true"
          make test
          make vet
          make testacc

          make stop-services
